services:
  server-tp:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-tp
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  client-tp:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-tp
    ports:
      - "5173:5173"
    networks:
      - app_network
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://server-tp:3000
    depends_on:
      server-tp:
        condition: service_healthy
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
