services:
  client-tp:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-tp
    ports:
      - "5173:5173"
    networks:
      - default
    env_file: "./client/.env"
    environment:
      - NODE_ENV=production
      - VITE_API_URL= http://bourbon.zapto.org:3000
    depends_on:
      - server-tp
    restart: always

  server-tp:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-tp
    ports:
      - "3000:3000"
    networks:
      - default
    environment:
      - NODE_ENV=production
    restart: always


networks:
  default:
    driver: bridge 
    
    
